export const connections: string
export const verticalMiddle: string
export const hoverActive: string
export const gitlab: string
export const medium: string
export const github: string
export const instagram: string
export const twitter: string
export const linkedin: string
export const mastodon: string
export const grow: string
