export const blur: string
export const canvas: string
export const bgImage: string
export const sidebar: string
export const sidebarHeader: string
export const avatar: string
export const quote: string
export const bg: string
export const jumbotron: string
export const container: string
