name: Test Coveralls

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build

    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - name: Use Node.js 18.x
        uses: actions/setup-node
        with:
          node-version: 18.x

      - name: run coverage
        run: |
          npm ci
          npm run test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
