on: ['push', 'pull_request']

name: Test Coveralls

jobs:
  build:
    name: Build

    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: run coverage
        run: |
          pnpm install
          pnpm run test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
